# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20170919_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplocation',
            name='ccity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='ccountry',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='clat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='clon',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='cstate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
