# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170830_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlss',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url]),
        ),
    ]
