# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='scode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortener.urlss'),
        ),
    ]
