# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_profiles_scode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='scode',
        ),
        migrations.AddField(
            model_name='urlss',
            name='owner',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
