# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20170909_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='reg_urls',
            field=models.ManyToManyField(to='shortener.urlss'),
        ),
    ]
