# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20170910_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlss',
            name='tag',
        ),
    ]
