# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_remove_urlss_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlss',
            name='tag',
            field=models.CharField(default='N.A.', max_length=15),
        ),
    ]
